---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      forward:
        - '8081:80/tcp'
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      forward:
        - '8080:80/tcp'

suites:
  - name: default
    data_bags_path: "test/data_bags"
    run_list:
      - recipe[aikcu-demo::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    #attributes: { "aikcu-demo": { "message": "Ohai!" } }
